config/routes.rb
Rails.application.routes.draw do

  namespace(:admin){ resources :media_types }
  namespace(:admin){ resources :user_levels }
  namespace(:admin){ resources :genres }
  namespace(:admin){ resources :actors }
  namespace(:admin){ resources :actor_countries }
  namespace(:admin){ resources :actor_genders }
  namespace(:admin){ resources :content_ratings }
  namespace :admin do
    resources :users
    resources :customers
    resources :inventories
    resources :videos do
      collection do
        get 'search'
      end
      resources :reviews, except: [:show, :index]
    end
    resources :movie_stocks
    resources :customers_movie_stocks_users
    root 'sessions#new'
  end
  resources :customers
  resources :movie_stocks
  resources :customers_movie_stocks_users
  resources :videos do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get '/signup', to: 'admin/users#new'
  post '/user_levels', to: 'admin/user_levels#create'
  get '/login', to: 'admin/sessions#new'
  post '/login', to: 'admin/sessions#create'
  delete '/admin_logout', to: 'admin/sessions#destroy'
  get '/admin_logout', to: 'admin/sessions#destroy'
#  get '/videos', to: 'dashboards#video'
  post '/video', to: 'admin/videos#create'
  #delete '/destroy_admin_video', to: 'admin/videos#destroy'
  post '/content_ratings', to: 'admin/content_ratings#create'
  post '/genres', to: 'admin/genres#create'
  post '/media_types', to: 'admin/media_types#create'
  #post '/actor_videos', to: 'videos#create'
  get '/rental', to: 'admin/dashboards#rental'
  get '/send_reminder_mail/:id', to: 'admin/mails#send_reminder_mail', as: 'admin_send_reminder_mail'
  get '/send_warning_mail/:id', to: 'admin/mails#send_warning_mail', as: 'admin_send_warning_mail'
  get '/send_wait_list_mail/:id', to: 'admin/mails#send_wait_list_mail', as: 'admin_send_wait_list_mail'

  get 'admin/mails/index'

  get 'admin/movie_stocks/index'
  get 'admin/movie_stocks/new'
  root 'static_pages#home'

  delete '/logout', to: 'customer_sessions#destroy'
  get '/logout', to: 'customer_sessions#destroy'
    #resources :actor_videos

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/customer_login', to: 'customer_sessions#new'
  post '/customer_login', to: 'customer_sessions#create'


end

app/models/customers_movie_stocks_user.rb
class CustomersMovieStocksUser < ApplicationRecord
  belongs_to :customer
  belongs_to :movie_stock
  belongs_to :user
  validates :price, presence: true
  validates :rented_date, presence: true
  validates :movie_stock_id, presence: true
  validates :customer_id, presence: true
  validates :user_id, presence: true
end

app/controllers/admin/customers_movie_stocks_users_controller.rb
class Admin::CustomersMovieStocksUsersController < Admin::BaseController
  before_action :set_customer_movie_stock_user, only: %i[ show edit update destroy ]

  # GET /customers_movie_stocks_users or /customers_movie_stocks_users.json
  def index
    @customers_movie_stocks_users = CustomersMovieStocksUser.all
  end

  # GET /customers_movie_stocks_users/1 or /customers_movie_stocks_users/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Rental No. #{@customer_movie_stock_user.id}",
        page_size: 'A4',
        template: "admin/customers_movie_stocks_users/show.html.erb",
        layout: "admin/pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  # GET /customers_movie_stocks_users/new
  def new
    @customer_movie_stock_user = CustomersMovieStocksUser.new
    @customer = Customer.new
    @movie_stock = MovieStock.new
    @user = User.new
  end

    # GET /customers_movie_stocks_users/1/edit
  def edit
  end

  # POST /customers_movie_stocks_users or /customers_movie_stocks_users.json
  def create
    @customer_movie_stock_user = CustomersMovieStocksUser.new(customer_movie_stock_user_params)
    @customer_movie_stock_user.user_id = current_user.id

    respond_to do |format|
      if @customer_movie_stock_user.save
        format.html { redirect_to [:admin, @customer_movie_stock_user], notice: "Rental was successfully created." }
        format.json { render :show, status: :created, location: @customer_movie_stock_user }

        format.html
        format.pdf do
          render pdf: "Rental No. #{@customer_movie_stock_user.id}",
          page_size: 'A4',
          template: "admin/customers_movie_stocks_users/show.html.erb",
          layout: "admin/pdf.html",
          orientation: "Landscape",
          lowquality: true,
          zoom: 1,
          dpi: 75
        end

          customer = Customer.find(params[:id])
          CustomerMailer.receipt(customer).deliver
          flash[:notice] = "Email has been sent."
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer_movie_stock_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers_movie_stocks_users/1 or /customers_movie_stocks_users/1.json
  def update
    respond_to do |format|
      if @customer_movie_stock_user.update(customer_movie_stock_user_params)
        format.html { redirect_to [:admin, @customer_movie_stock_user], notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @customer_movie_stock_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer_movie_stock_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers_movie_stocks_users/1 or /customers_movie_stocks_users/1.json
  def destroy
    @customer_movie_stock_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_customers_movie_stocks_users_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_movie_stock_user
      @customer_movie_stock_user = CustomersMovieStocksUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_movie_stock_user_params
      params.require(:customers_movie_stocks_user).permit(:price, :late_fee, :discount, :rented_date, :returned_date, :customer_id, :movie_stock_id)
    end
end

app/controllers/customers_movie_stocks_users_controller.rb
class CustomersMovieStocksUsersController < ApplicationController
  before_action :set_customer_movie_stock_user, only: %i[ show edit update destroy ]
  before_action :require_login
  # GET /customers_movie_stocks_users or /customers_movie_stocks_users.json
  def index

    @customers_movie_stocks_users = CustomersMovieStocksUser.where(customer_id: current_user.id)
  end

  # GET /customers_movie_stocks_users/1 or /customers_movie_stocks_users/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Rental No. #{@customer_movie_stock_user.id}",
        page_size: 'A4',
        template: "customers_movie_stocks_users/show.html.erb",
        layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  # GET /customers_movie_stocks_users/new
  def new
    @customer_movie_stock_user = CustomersMovieStocksUser.new
    @customer = Customer.new
    @movie_stock = MovieStock.new
    @user = User.new
  end

    # GET /customers_movie_stocks_users/1/edit
  def edit
  end

  # POST /customers_movie_stocks_users or /customers_movie_stocks_userscustomers_movie_stocks_users.json
  def create
    @customer_movie_stock_user = CustomersMovieStocksUser.new(customer_movie_stock_user_params)
    @customer_movie_stock_user.customer_id = current_user.id

    respond_to do |format|
      if @customer_movie_stock_user.save
        format.html { redirect_to  @customer_movie_stock_user, notice: "Rental was successfully created." }
        format.json { render :show, status: :created, location: @customer_movie_stock_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer_movie_stock_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers_movie_stocks_users/1 or /customers_movie_stocks_users/1.json
  def update
    respond_to do |format|
      if @customer_movie_stock_user.update(customer_movie_stock_user_params)
        format.html { redirect_to @customer_movie_stock_user, notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @customer_movie_stock_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer_movie_stock_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers_movie_stocks_users/1 or /customers_movie_stocks_users/1.json
  def destroy
    @customer_movie_stock_user.destroy
    respond_to do |format|
      format.html { redirect_to customers_movie_stocks_users_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_movie_stock_user
      @customer_movie_stock_user = CustomersMovieStocksUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_movie_stock_user_params
      params.require(:customers_movie_stocks_user).permit(:price, :rented_date, :user_id)
    end

    def require_login
      unless current_user
        redirect_to customer_login_path

      end
    end
end

app/helpers/admin/customers_movie_stocks_users_helper.rb
module Admin::CustomersMovieStocksUsersHelper


end

app/helpers/customers_movie_stocks_users_helper.rb
module CustomersMovieStocksUsersHelper


end

app/views/admin/customers_movie_stocks_users/_form.html.erb
<%= form_with(model: [:admin, customers_movie_stocks_user], local: true) do |form| %>
  <% if customers_movie_stocks_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customers_movie_stocks_user.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% customers_movie_stocks_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :late_fee %>
    <%= form.text_field :late_fee %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :rented_date %>
    <%= form.date_field :rented_date %>
  </div>

  <div class="field">
    <%= form.label :returned_date %>
    <%= form.date_field :returned_date %>
  </div>

  <div class="field" id="customer">
    <%= form.label :customers %>
    <%= form.collection_select :customer_id, Customer.all,
                          :id, :name, class: 'form-control'%><br>
  </div>

  <div class="field" id="movie_stock">
    <%= form.label :movie_stocks %>
    <%= form.collection_select :movie_stock_id, MovieStock.all,
                          :id, :id, class: 'form-controll' %><br>
  </div>

  <!--div class="field" id="user">
    <%= form.label :users %>
    <%= form.collection_select :user_id, User.order(:name),
                          :id, :name, class: 'form-control' %><br>
  </div-->

  <div class="actions">
    <%= form.submit "Create the Rental" %>
  </div>
<% end %>

app/views/admin/customers_movie_stocks_users/edit.html.erb
<h1>Editing Rentals</h1>

<%= render 'form', customers_movie_stocks_user: @customer_movie_stock_user %>

<%= link_to 'Show', admin_customers_movie_stocks_user_path %> |
<%= link_to 'All Rentals', admin_customers_movie_stocks_users_path %>

app/views/admin/customers_movie_stocks_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Rental ID</th>
      <th>Price</th>
      <th>Late Fee</th>
      <th>Discount</th>
      <th>Rented Date</th>
      <th>Returned Date</th>
      <th>Customer</th>
      <th>Movie Stock</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers_movie_stocks_users.each do |customer_movie_stock_user| %>
      <tr>
        <td><%= customer_movie_stock_user.id %></td>
        <td><%= customer_movie_stock_user.price %></td>
        <td><%= customer_movie_stock_user.late_fee %></td>
        <td><%= customer_movie_stock_user.discount %></td>
        <td><%= customer_movie_stock_user.rented_date %></td>
        <td><%= customer_movie_stock_user.returned_date %></td>
        <td><%= customer_movie_stock_user.customer.name %></td>
        <td><%= customer_movie_stock_user.movie_stock_id %></td>
        <td><%= customer_movie_stock_user.user.name %></td>
        <td><%= link_to 'Show', admin_customers_movie_stocks_user_path(customer_movie_stock_user) %></td>
        <td><%= link_to 'Edit', edit_admin_customers_movie_stocks_user_path(customer_movie_stock_user) %></td>
        <% if log_in_as_super_user? || log_in_as_admin_user? %>
          <td><%= button_to 'Destroy', admin_customers_movie_stocks_user_path(customer_movie_stock_user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_admin_customers_movie_stocks_user_path %>

app/views/admin/customers_movie_stocks_users/new.html.erb
<% provide(:title, 'Rental') %>
<h1>New Rentals</h1>

<div class="row">

  <div class="col-md-6 col-md-offset-3" id="add-rental">
    <%= render 'form', customers_movie_stocks_user: @customer_movie_stock_user %>
  </div>
</div>


<%= link_to 'Back', admin_customers_movie_stocks_users_path %>

app/views/admin/customers_movie_stocks_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rental ID:</strong>
  <%= @customer_movie_stock_user.id %>
</p>

<p>
  <strong>Video:</strong>
  <%= @customer_movie_stock_user.movie_stock.inventory.video.title %>
</p>

<p>
  <strong>Media Type:</strong>
  <%= @customer_movie_stock_user.movie_stock.inventory.media_type.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @customer_movie_stock_user.price %>
</p>

<p>
  <strong>Late Fee:</strong>
  <%= @customer_movie_stock_user.late_fee %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @customer_movie_stock_user.discount %>
</p>

<p>
  <strong>Rented Date:</strong>
  <%= @customer_movie_stock_user.rented_date %>
</p>

<p>
  <strong>Returned Date:</strong>
  <%= @customer_movie_stock_user.returned_date %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @customer_movie_stock_user.customer.name %>
</p>

<p>
  <strong>Movie Stock:</strong>
  <%= @customer_movie_stock_user.movie_stock_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @customer_movie_stock_user.user.name %>
</p>

<% if @customer_movie_stock_user.returned_date.present? %>
  <%= link_to 'Print PDF', admin_customers_movie_stocks_user_path(@customer_movie_stock_user, format: "pdf") %> |
<% else %>
  <%= link_to 'Make a Rent', new_admin_customers_movie_stocks_user_path %> |
<% end %>
<%= link_to 'Edit', edit_admin_customers_movie_stocks_user_path(@customer_movie_stock_user) %> |
<%= link_to 'Back', admin_customers_movie_stocks_users_path %>