config/routes.rb
Rails.application.routes.draw do

  namespace(:admin){ resources :media_types }
  namespace(:admin){ resources :user_levels }
  namespace(:admin){ resources :genres }
  namespace(:admin){ resources :actors }
  namespace(:admin){ resources :actor_countries }
  namespace(:admin){ resources :actor_genders }
  namespace(:admin){ resources :content_ratings }
  namespace :admin do
    resources :users
    resources :customers
    resources :inventories
    resources :videos do
      collection do
        get 'search'
      end
      resources :reviews, except: [:show, :index]
    end
    resources :movie_stocks
    resources :customers_movie_stocks_users
    root 'sessions#new'
  end
  resources :customers
  resources :movie_stocks
  resources :customers_movie_stocks_users
  resources :videos do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get '/signup', to: 'admin/users#new'
  post '/user_levels', to: 'admin/user_levels#create'
  get '/login', to: 'admin/sessions#new'
  post '/login', to: 'admin/sessions#create'
  delete '/admin_logout', to: 'admin/sessions#destroy'
  get '/admin_logout', to: 'admin/sessions#destroy'
#  get '/videos', to: 'dashboards#video'
  post '/video', to: 'admin/videos#create'
  #delete '/destroy_admin_video', to: 'admin/videos#destroy'
  post '/content_ratings', to: 'admin/content_ratings#create'
  post '/genres', to: 'admin/genres#create'
  post '/media_types', to: 'admin/media_types#create'
  #post '/actor_videos', to: 'videos#create'
  get '/rental', to: 'admin/dashboards#rental'
  get '/send_reminder_mail/:id', to: 'admin/mails#send_reminder_mail', as: 'admin_send_reminder_mail'
  get '/send_warning_mail/:id', to: 'admin/mails#send_warning_mail', as: 'admin_send_warning_mail'
  get '/send_wait_list_mail/:id', to: 'admin/mails#send_wait_list_mail', as: 'admin_send_wait_list_mail'

  get 'admin/mails/index'

  get 'admin/movie_stocks/index'
  get 'admin/movie_stocks/new'
  root 'static_pages#home'

  delete '/logout', to: 'customer_sessions#destroy'
  get '/logout', to: 'customer_sessions#destroy'
    #resources :actor_videos

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/customer_login', to: 'customer_sessions#new'
  post '/customer_login', to: 'customer_sessions#create'


end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :customers_movie_stocks_users
  has_many :movie_stocks, :through => :customers_movie_stocks_users
  has_many :users, :through => :customers_movie_stocks_users
  has_many :videos, :through => :reviews
  has_many :reviews, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::BaseController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  def send_mail
    @customer = CustomerMailer.reminder
  end

  def send_reminder_mail(customer)
    @customer = customer
    CustomerMailer.reminder([:admin, @customer]).deliver_now!
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to [:admin, @customer], notice: "Customer was successfully created." }
        format.json { render :admin_customer_path, status: :created, location: [:admin, @customer] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to [:admin, @customer], notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: [:admin, @customer] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: [:admin, @customer].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to admin_customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email, :password)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update ]

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :email, :password)
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper

end

app/helpers/customers_helper.rb
module CustomersHelper

end

app/views/admin/customers/_form.html.erb
<%= form_for [:admin, @customer], html: {multipart: true} do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', admin_customer_path(@customer) %> |
<%= link_to 'Back', admin_customers_path %>

app/views/admin/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.password_digest %></td>
        <td><%= link_to 'Show', admin_customer_path(customer) %></td>
        <% if log_in_as_super_user? || log_in_as_admin_user? %>
          <td><%= link_to 'Edit', edit_admin_customer_path(customer) %></td>
        <% end %>
        <% if log_in_as_super_user? || log_in_as_admin_user? %>
          <td><%= button_to 'Destroy', admin_customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if log_in_as_super_user? || log_in_as_admin_user? %>
  <%= link_to 'New Customer', new_admin_customer_path %>
<% end %>

app/views/admin/customers/new.html.erb
<% if log_in_as_super_user? || log_in_as_admin_user? %>
  <h1>New Customer</h1>

  <%= render 'form', admin_customer: @admin_customer %>


    <%= link_to 'Back', admin_customers_path %>
<% else %>
  redirect_to admin_customer_path
<% end %>

app/views/admin/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @customer.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @customer.password_digest %>
</p>

<%= link_to 'Send Reminder', admin_send_reminder_mail_path %> |
<%= link_to 'Send Warning', admin_send_warning_mail_path %> |
<%= link_to 'Send WaitList Mail', admin_send_wait_list_mail_path %> |

<% if log_in_as_super_user? || log_in_as_admin_user? %>
  <%= link_to 'Edit', edit_admin_customer_path(@customer) %> |
<% end %>
<%= link_to 'Back', admin_customers_path %>