config/routes.rb
Rails.application.routes.draw do

  namespace(:admin){ resources :media_types }
  namespace(:admin){ resources :user_levels }
  namespace(:admin){ resources :genres }
  namespace(:admin){ resources :actors }
  namespace(:admin){ resources :actor_countries }
  namespace(:admin){ resources :actor_genders }
  namespace(:admin){ resources :content_ratings }
  namespace :admin do
    resources :users
    resources :customers
    resources :inventories
    resources :videos do
      collection do
        get 'search'
      end
      resources :reviews, except: [:show, :index]
    end
    resources :movie_stocks
    resources :customers_movie_stocks_users
    root 'sessions#new'
  end
  resources :customers
  resources :movie_stocks
  resources :customers_movie_stocks_users
  resources :videos do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get '/signup', to: 'admin/users#new'
  post '/user_levels', to: 'admin/user_levels#create'
  get '/login', to: 'admin/sessions#new'
  post '/login', to: 'admin/sessions#create'
  delete '/admin_logout', to: 'admin/sessions#destroy'
  get '/admin_logout', to: 'admin/sessions#destroy'
#  get '/videos', to: 'dashboards#video'
  post '/video', to: 'admin/videos#create'
  #delete '/destroy_admin_video', to: 'admin/videos#destroy'
  post '/content_ratings', to: 'admin/content_ratings#create'
  post '/genres', to: 'admin/genres#create'
  post '/media_types', to: 'admin/media_types#create'
  #post '/actor_videos', to: 'videos#create'
  get '/rental', to: 'admin/dashboards#rental'
  get '/send_reminder_mail/:id', to: 'admin/mails#send_reminder_mail', as: 'admin_send_reminder_mail'
  get '/send_warning_mail/:id', to: 'admin/mails#send_warning_mail', as: 'admin_send_warning_mail'
  get '/send_wait_list_mail/:id', to: 'admin/mails#send_wait_list_mail', as: 'admin_send_wait_list_mail'

  get 'admin/mails/index'

  get 'admin/movie_stocks/index'
  get 'admin/movie_stocks/new'
  root 'static_pages#home'

  delete '/logout', to: 'customer_sessions#destroy'
  get '/logout', to: 'customer_sessions#destroy'
    #resources :actor_videos

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/customer_login', to: 'customer_sessions#new'
  post '/customer_login', to: 'customer_sessions#create'


end

app/models/actor.rb
class Actor < ActiveRecord::Base
  belongs_to :actor_gender
  belongs_to :actor_country
  has_many :actors_videos
  has_many :videos, through: :actors_videos
  validates :name, presence: true
  validates :age, presence: true
  validates :actor_gender_id, presence: true
  validates :actor_country_id, presence: true
end

app/models/actor_country.rb
class ActorCountry < ActiveRecord::Base
  has_many :actors
  validates :name, presence: true
end

app/models/actor_gender.rb
class ActorGender < ActiveRecord::Base
  has_many :actors
  validates :gender, presence: true
end

app/models/actors_video.rb
class ActorsVideo < ApplicationRecord
  belongs_to :video
  belongs_to :actor
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content_rating.rb
class ContentRating < ActiveRecord::Base
  has_many :videos
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :customers_movie_stocks_users
  has_many :movie_stocks, :through => :customers_movie_stocks_users
  has_many :users, :through => :customers_movie_stocks_users
  has_many :videos, :through => :reviews
  has_many :reviews, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :genres_videos
  has_many :videos, through: :genres_videos
  validates :name, presence: true
end

app/models/genres_video.rb
class GenresVideo < ApplicationRecord
  belongs_to :video
  belongs_to :genre
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :video
  belongs_to :media_type
  has_many :movie_stocks, dependent: :destroy
  validates :price, presence: true
  validates :total_copies, presence: true
  validates :barcode_no, presence: true
  validates :media_type_id, presence: true
  validates :video_id, presence: true
end

app/models/media_type.rb
class MediaType < ActiveRecord::Base
  has_many :inventories
  validates :name, presence: true
end

app/models/movie_stock.rb
class MovieStock < ApplicationRecord
  belongs_to :inventory
  has_many :customers_movie_stocks_users
  has_many :customers, :through => :customers_movie_stocks_users
  has_many :users, :through => :customers_movie_stocks_users
  validates :is_rented, presence: true
  validates :inventory_id, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :video
  validates :rating, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :user_level
  has_many :customers_movie_stocks_users
  has_many :customers, :through => :customers_movie_stocks_users
  has_many :movie_stocks, :through => :customers_movie_stocks_users
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :user_level_id, presence: true
end

app/models/user_level.rb
class UserLevel < ActiveRecord::Base
  has_many :users
  validates :level, presence: true
end

app/models/video.rb
class Video < ApplicationRecord
  searchkick
  has_many :actors_videos
  has_many :actors, through: :actors_videos
  belongs_to :content_rating
  has_many :inventories, dependent: :destroy
  has_many :media_type, :through => :inventories
  has_many :genres_videos, dependent: :destroy
  has_many :genres, :through => :genres_videos
  has_many :customers, :through => :reviews
  has_many :reviews, dependent: :destroy
  has_attached_file :thumbnail, styles: {medium: "200*300"}
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/
  validates :title, presence: true
  validates :description, presence: true
  validates :thumbnail, presence: true
  validates :release_date, presence: true
  validates :content_rating_id, presence: true

  def self.search_by(search_term)
    where("LOWER(title) LIKE :search_term", search_term: "%#{search_term.downcase}%").uniq
  end
end

app/helpers/customers_helper.rb
module CustomersHelper

end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def current_customer
    if session[:customer_id]
      @current_customer ||= Customer.find_by(id: session[:customer_id])
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/admin/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Admin Layout</a>
    by <a href="https://www.michaelhartl.com/">Daham Wijekoon</a>
  </small>
  <nav>
    <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MovieStore", admin_root_path, id: "logo" %>
    <nav>
      <%= form_tag admin_videos_path, method: :get, class: "navbar-form navbar-left", role: "search" do %>
        <p>
          <%= search_field_tag :search, @search_term, class: "form-control", id: "search-field" %>
          <%= button_tag "Search", name: nil, class: "btn btn-default", id: "search" %>
        </p>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",admin_root_path %></li>
        <li><%= link_to "Help",help_path %></li>
        <% if !current_user.nil? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Videos<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Actors", new_admin_actor_path %></li>
              <li><%= link_to "Actor Genders", new_admin_actor_gender_path %></li>
              <li><%= link_to "Actor Countries", new_admin_actor_country_path %></li>
              <li><%= link_to "Content Rating", new_admin_content_rating_path %></li>
              <li><%= link_to "Genres", new_admin_genre_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "New Video", new_admin_video_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% if log_in_as_super_user? || log_in_as_admin_user? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "User Levels", admin_user_levels_path%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "New User", signup_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", admin_user_path(current_user) %></li>
              <li><%= link_to "Inventories", admin_inventories_path %></li>
              <li><%= link_to "Movie Stocks", admin_movie_stocks_path %></li>
              <li><%= link_to "Rentals", admin_customers_movie_stocks_users_path %></li>
              <li><%= link_to "Customers", admin_customers_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", admin_logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Login", admin_root_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/admin/header' %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/admin/footer' %>
    </div>
  </body>
</html>

app/views/layouts/admin/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PDFs | Ruby on Rails</title>
      
    </head>
  <body>
    <%= yield %>
  </body>
</html>