config/routes.rb
Rails.application.routes.draw do

  namespace(:admin){ resources :media_types }
  namespace(:admin){ resources :user_levels }
  namespace(:admin){ resources :genres }
  namespace(:admin){ resources :actors }
  namespace(:admin){ resources :actor_countries }
  namespace(:admin){ resources :actor_genders }
  namespace(:admin){ resources :content_ratings }
  namespace :admin do
    resources :users
    resources :customers
    resources :inventories
    resources :videos do
      collection do
        get 'search'
      end
      resources :reviews, except: [:show, :index]
    end
    resources :movie_stocks
    resources :customers_movie_stocks_users
    root 'sessions#new'
  end
  resources :customers
  resources :movie_stocks
  resources :customers_movie_stocks_users
  resources :videos do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get '/signup', to: 'admin/users#new'
  post '/user_levels', to: 'admin/user_levels#create'
  get '/login', to: 'admin/sessions#new'
  post '/login', to: 'admin/sessions#create'
  delete '/admin_logout', to: 'admin/sessions#destroy'
  get '/admin_logout', to: 'admin/sessions#destroy'
#  get '/videos', to: 'dashboards#video'
  post '/video', to: 'admin/videos#create'
  #delete '/destroy_admin_video', to: 'admin/videos#destroy'
  post '/content_ratings', to: 'admin/content_ratings#create'
  post '/genres', to: 'admin/genres#create'
  post '/media_types', to: 'admin/media_types#create'
  #post '/actor_videos', to: 'videos#create'
  get '/rental', to: 'admin/dashboards#rental'
  get '/send_reminder_mail/:id', to: 'admin/mails#send_reminder_mail', as: 'admin_send_reminder_mail'
  get '/send_warning_mail/:id', to: 'admin/mails#send_warning_mail', as: 'admin_send_warning_mail'
  get '/send_wait_list_mail/:id', to: 'admin/mails#send_wait_list_mail', as: 'admin_send_wait_list_mail'

  get 'admin/mails/index'

  get 'admin/movie_stocks/index'
  get 'admin/movie_stocks/new'
  root 'static_pages#home'

  delete '/logout', to: 'customer_sessions#destroy'
  get '/logout', to: 'customer_sessions#destroy'
    #resources :actor_videos

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/customer_login', to: 'customer_sessions#new'
  post '/customer_login', to: 'customer_sessions#create'


end

app/models/video.rb
class Video < ApplicationRecord
  searchkick
  has_many :actors_videos
  has_many :actors, through: :actors_videos
  belongs_to :content_rating
  has_many :inventories, dependent: :destroy
  has_many :media_type, :through => :inventories
  has_many :genres_videos, dependent: :destroy
  has_many :genres, :through => :genres_videos
  has_many :customers, :through => :reviews
  has_many :reviews, dependent: :destroy
  has_attached_file :thumbnail, styles: {medium: "200*300"}
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/
  validates :title, presence: true
  validates :description, presence: true
  validates :thumbnail, presence: true
  validates :release_date, presence: true
  validates :content_rating_id, presence: true

  def self.search_by(search_term)
    where("LOWER(title) LIKE :search_term", search_term: "%#{search_term.downcase}%").uniq
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos =Video.order("created_at DESC")
    if params[:search]
      @search_term = params[:search]
      @videos = @videos.search_by(@search_term)
    end
  end

  # GET /videos/1 or /videos/1.json
  def show
    @review = Review.where(video_id: @video.id).order("created_at DESC")

    if @review.blank?
      @avg_review = 0
    else
      @avg_review = @review.average(:rating).round(2)
    end
  end

  # GET /videos/new
  def new
    @video = Video.new
    @content_rating = ContentRating.new
    @genre = Genre.new
    @actor = Actor.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    @review = Review.where(video_id: @video.id)

    if @review.blank?
      @video.rating = 0
    else
      @video.rating = @review.average(:rating).round(2)
    end


    respond_to do |format|
      if @video.save

        format.html { redirect_to [:admin, @video], notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: [:admin, @video] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: [:admin, @video].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to [:admin, @video], notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: [:admin, @video] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: [:admin, @video].errors, status: :unprocessable_entity }
      end
    end
  end

    # DELETE /videos/1 or /videos/1.json
  def destroy

    respond_to do |format|
      if @video.destroy
        format.html { redirect_to admin_videos_url, notice: "Video was successfully destroyed." }
        format.json { head :no_content }
      end

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :release_date, :content_rating_id, :thumbnail, :actor_ids=>[], :genre_ids=>[])
    end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show ]

  # GET /videos or /videos.json
  def index
    @videos =Video.order("created_at DESC")
    if params[:search]
      @search_term = params[:search]
      @videos = @videos.search_by(@search_term)
    end
  end

  # GET /videos/1 or /videos/1.json
  def show
    @review = Review.where(video_id: @video.id).order("created_at DESC")

    if @review.blank?
      @avg_review = 0
    else
      @avg_review = @review.average(:rating).round(2)
    end
  end

  def create

    @review = Review.where(video_id: @video.id)

    if @review.blank?
      @video.rating = 1
    else
      @video.rating = @review.average(:rating).round(2)
    end


    respond_to do |format|
      if @review.save

        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

end

app/helpers/admin/videos_helper.rb
module Admin::VideosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_form.html.erb
<%= form_for [:admin, @video], html: {multipart: true} do |form| %>
  <%= render 'admin/shared/video_error_messages' %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field", id="thumbnail">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="field", id="release-date">
    <%= form.label :release_date %>
    <%= form.date_field :release_date %>
  </div>

  <div class="field", id="content-rating">
    <%= form.label :content_rating %>
    <%= form.collection_select :content_rating_id, ContentRating.all,
                          :id, :name, class: 'form-control' %><br>
  </div>

  <div class="field", id="actors">
    <%= form.label :actors %>
    <%= form.collection_select :actor_ids, Actor.order(:name),
                          :id, :name, {}, {class: 'form-control select2', multiple: true } %><br>
  </div>

  <div class="field", id="genres">
    <%= form.label :genres %>
    <%= form.collection_select :genre_ids, Genre.order(:name),
                          :id, :name, {}, {class: 'form-control select2', multiple: true } %><br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', admin_video_path(@video) %> |
<%= link_to 'Back', admin_videos_path %>

app/views/admin/videos/index.html.erb
<div class="row">
  <% @videos.each do |video| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <li id="image"><%= link_to (image_tag video.thumbnail.url(:medium), class: 'thumbnail'), admin_video_path(video) %></li>
        <% if log_in_as_super_user? || log_in_as_admin_user? %>
          <%= button_to 'Destroy', admin_video_path(video), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

<%= link_to 'New Video', new_admin_video_path %>

app/views/admin/videos/new.html.erb
<% provide(:title, 'Video') %>
<h1>New Video</h1>

<div class="row">

  <div class="col-md-6 col-md-offset-3" id="add-video">
    <%= render 'form', admin_video: @admin_video %>
  </div>

</div>



<%= link_to 'Videos List', admin_videos_path %>

app/views/admin/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @video.thumbnail.url(:medium) %>
        <p> <%= @avg_review %> </p>
          <em><%= "#{@review.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @video.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @video.description %></td>
              </tr>
              <tr>
                <td><strong>Release date:</strong></td>
                <td><%= @video.release_date %></td>
              </tr>
              <tr>
                <td><strong>Content Rating:</strong></td>
                <td><%= @video.content_rating.name %></td>
              </tr>
              <tr>
                <td><strong>Genres:</strong></td>
                <td>
                  <% @video.genre_ids.each do |genre| %>
                    <%= Genre.find(genre).name %> |
                  <% end %>
                </td>
              </tr>
              <tr>
                <td><strong>Actors:</strong></td>
                <td>
                  <% @video.actor_ids.each do |actor| %>
                    <%= Actor.find(actor).name %> |
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-7 col-d-offset-1">
        <h1 class="review-title"><%= @video.title %></h1>
        <p><%= @video.description %></p>
        <% if @review.blank? %>
          <h3>No reviews just yet!</h3>
        <% else %>
          <% @review.each do |review| %>
            <div class="reviews">
              <p><%= review.rating %></p>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if log_in_as_super_user? || log_in_as_admin_user? %>
  <%= link_to 'Edit', edit_admin_video_path(@video) %> |
  <%= link_to 'Back', admin_videos_path %>
<% end %>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>